### ISSUE TITLE
Create example w/ mixed hbs + js and link in the readme

### ISSUE THREAD

**Issue by toranb** [toranb/ember-cli-hot-loader#13]
@MiguelMadero we have one example in the README now to show inline hbs working but I was hoping you could setup an example app using mixed hbs + js and add that link (calling out one as inline and one as hbs) ?

**Comment by toranb** [comment]
Also - I noticed the readme still has a "pods and inline hbs required" - if that's not true could you submit a PR removing them this week? thank you sir :)

**Comment by MiguelMadero** [comment]
Sure

**Comment by MiguelMadero** [comment]
> I noticed the readme still has a "pods and inline hbs required"

That's removed now. 

> we have one example in the README now to show inline hbs working but I was hoping you could setup an example app using mixed hbs + js

I think it's good the way it's until we fix https://github.com/toranb/ember-cli-hot-loader/issues/5 we probably don't want to list the different scenarios. Once we do, I don't think that making that distinction should be in the README. I would rather say that we support "all components", any scenario that doesn't work I would consider that a bug. 

That said, I have a sample app on https://github.com/ember-samples/hot-reloaded-app and it shows all the main scenarios (missing addon support)

**Comment by MiguelMadero** [comment]
Scratch that, I moved the samples to dummy app, see https://github.com/toranb/ember-cli-hot-loader/pull/17 

I hope we somehow can add some node/acceptance tests to automate this.
