### ISSUE TITLE
Add support for 1.13+

### ISSUE THREAD

**Issue by MiguelMadero** [toranb/ember-cli-hot-loader#16]
Moved from https://github.com/toranb/ember-hot-reload-spike/issues/1

I ran into some owner api changes from 2.7 -> back to 2.0.3

1) use the polyfill

import getOwner from 'ember-getowner-polyfill';
2) use this api to reload JS changes

    owner = getOwner(wrapper);
    owner.ownerInjection().container.cache[name] = undefined;
    owner.ownerInjection().container.factoryCache[name] = undefined;
    owner.ownerInjection().container._registry._resolveCache[name] = undefined;
    owner.ownerInjection().container._registry._failCache[name] = undefined;
One issue I found tonight is that templates (hbs changes) won't reload without the owner.base and I'm not yet certain how to get this info from the polyfill API

**Comment by MiguelMadero** [comment]
@toranb I think instead of getting the owner.base, we can probably `getOwener(owner.lookup('route:application')` or ``getOwener(owner.lookup('application:main')`. Totally untested, but just wanted to throw the idea here so either of us can test it when we start working on this issue. 

Once we have mixed component support I'll give it a go since I need 1.13 support.

**Comment by toranb** [comment]
1.13 support would be awesome -using it on some legacy projects at the moment so I'm glad the hacky ember 2x support spike I did was worth something after all
