### ISSUE TITLE
Test a component with a yielded block and positional params

### ISSUE THREAD

**Issue by MiguelMadero** [toranb/ember-cli-hot-loader#22]
[Reported on twitter](https://twitter.com/SirZach/status/780556212723212288)

Here is a rough idea: 

```
{{#my-component positionalParam1}}
  <div>here is a block</div>
{{/my-component}}
```

**Comment by toranb** [comment]
@MiguelMadero great find- I'll see if I can give this a look (mostly to refresh my understanding of the wrapper component and how we are feeding it positionalParams)

If you find time to beat me to it that's cool also :)

**Comment by MiguelMadero** [comment]
Sounds good. I'll assign it to you to avoid duplicating efforts. Thanks

**Comment by toranb** [comment]
@MiguelMadero I created a short example of what I assume this looks like and it seems to be working fine with ember 2.7.3 / ember-cli 2.7.0 / node v4 and v5

https://github.com/toranb/ember-cli-hot-loader/commit/f8adb16e06e2009acc6c61b9d9b400894a92b88a

I'll reach out on twitter to see what other details I can learn to better reproduce this

![positionalparamerror](https://cloud.githubusercontent.com/assets/147411/18911833/c29ee12e-8544-11e6-863b-6d51eb3268c9.gif)

**Comment by SirZach** [comment]
Ok I'm using ember 2.4.6. My component wasn't using positional params but the `hot-load-component` bombed on its own positional params.

**Comment by SirZach** [comment]
i think it was https://github.com/toranb/ember-cli-hot-loader/blob/master/addon/components/hot-replacement-component.js#L33 this guy.

**Comment by MiguelMadero** [comment]
The problem might be if the component supports positional params, but the
consumer doesn't pass them....

**Comment by toranb** [comment]
@MiguelMadero is that a valid use case in general? Just curious - likely I don't understand *literally this was my first use of positional params so be gentle :)

**Comment by MiguelMadero** [comment]
@toranb yes, that's a valid use. I'm trying to repro now. Take `{{link-to}}` as an example (from [the guides](https://guides.emberjs.com/v2.5.0/templates/links/)):

```
{{#link-to "photos.edit" photo}}{{photo.title}}{{/link-to}}
```

vs my made-up example

```
  {{link-to "route-without-dynamic-segments"}}
```

So we can pass 0 to N positional params depending on how many dynamic segments do we have. I think I'm doing the wrong thing of always "applying" all the params...

**Comment by MiguelMadero** [comment]
Ok. I can repro with the following: 

```diff
diff --git a/tests/dummy/app/templates/application.hbs b/tests/dummy/app/templates/application.hbs
index 18d5cd2..3dac1c8 100644
--- a/tests/dummy/app/templates/application.hbs
+++ b/tests/dummy/app/templates/application.hbs
@@ -16,3 +16,7 @@ JS Only pod: {{js-only-pod}}
 {{template-only-classic}}
 <h2>template-only-pod</h2>
 {{template-only-pod}}
+<h2>positional-params</h2>
+{{#positional-params}}
+  From yielded block
+{{/positional-params}}
~/code/ember-cli-hot-loader [master|✚ 1…2] 
08:07 AM $ gitx 
~/code/ember-cli-hot-loader [master|✚ 1…2] 
08:07 AM $ git add . 
~/code/ember-cli-hot-loader [master|● 3] 
08:07 AM $ git diff --staged 
diff --git a/tests/dummy/app/components/positional-params.js b/tests/dummy/app/components/positional-params.js
new file mode 100644
index 0000000..30fab80
--- /dev/null
+++ b/tests/dummy/app/components/positional-params.js
@@ -0,0 +1,13 @@
+import Ember from 'ember';
+import layout from '../templates/components/positional-params';
+
+const PositionalParamsComponent = Ember.Component.extend({
+  layout,
+  x: 2,
+  y: 3,
+  z: 4
+});
+PositionalParamsComponent.reopenClass({
+  positionalParams: ['x', 'y', 'z']
+});
+export default PositionalParamsComponent;
diff --git a/tests/dummy/app/templates/application.hbs b/tests/dummy/app/templates/application.hbs
index 18d5cd2..3dac1c8 100644
--- a/tests/dummy/app/templates/application.hbs
+++ b/tests/dummy/app/templates/application.hbs
@@ -16,3 +16,7 @@ JS Only pod: {{js-only-pod}}
 {{template-only-classic}}
 <h2>template-only-pod</h2>
 {{template-only-pod}}
+<h2>positional-params</h2>
+{{#positional-params}}
+  From yielded block
+{{/positional-params}}
diff --git a/tests/dummy/app/templates/components/positional-params.hbs b/tests/dummy/app/templates/components/positional-params.hbs
new file mode 100644
index 0000000..1456b87
--- /dev/null
+++ b/tests/dummy/app/templates/components/positional-params.hbs
@@ -0,0 +1,2 @@
+{{x}}-{{y}}-{{z}}
+{{yield}}
```

Basically, we have a component with positional params with default values, when we component-apply we are overriding all the default params with null values, even tho the consumer doesn't pass them, `hot-replacement-component` always does. 

Here is my current thinking? 

Option 1: Move away from component-apply in favor of AST transforms, this will solve this problem and likely also https://github.com/toranb/ember-cli-hot-loader/issues/24, maybe https://github.com/toranb/ember-cli-hot-loader/pull/23 and it will also remove the need to have a resolver (at least for now). 
Option 2: we may be able to inspect which properties were passed as positional params and only "apply" those. If we fix this here, we may want to move this upstream to https://github.com/zenefits/ember-component-apply

**Comment by MiguelMadero** [comment]
As I mentioned on https://github.com/toranb/ember-cli-hot-loader/pull/25 fixes this. I'll leave this open until we merge that PR.

**Comment by toranb** [comment]
Closing old issues as I prepare for the v1.0 release later this month. If you get involved or have more bandwidth in the future to persue this just let me know
