### ISSUE TITLE
tagless components

### ISSUE THREAD

**Issue by SirZach** [toranb/ember-cli-hot-loader#24]
I have some tagless components that bomb when I'm using the `HotReloadMixin` in the resolver.

`ember.debug.js:6382 Uncaught Error: Assertion Failed: You can not define a function that handles DOM events in the`<nui@component:fa-icon::ember1386>`tagless component since it doesn't have any DOM element.`

If I take out the `HotReloadMixin` out of the resolver, I don't have any issues.

**Comment by toranb** [comment]
@MiguelMadero is it even possible that we will be able to support tagless components given the current implementation? It would appear that using our proxy the net result is a tagless component wrapping a tagless component (child).

**Comment by MiguelMadero** [comment]
nested tagless components is a valid scenario. @SirZach do you have repro steps? Is this something you can throw on a branch and add a component to the dummy project. I did the following and couldn't repro. 

```
diff --git a/tests/dummy/app/templates/application.hbs b/tests/dummy/app/templates/application.hbs
index 18d5cd2..bd4e21c 100644
--- a/tests/dummy/app/templates/application.hbs
+++ b/tests/dummy/app/templates/application.hbs
@@ -16,3 +16,6 @@ JS Only pod: {{js-only-pod}}
 {{template-only-classic}}
 <h2>template-only-pod</h2>
 {{template-only-pod}}
+
+<h2>tagless</h2>
+{{tagless-component}}
diff --git a/tests/dummy/app/templates/components/tagless-component.hbs b/tests/dummy/app/templates/components/tagless-component.hbs
index 879361d..e8781f1 100644
--- a/tests/dummy/app/templates/components/tagless-component.hbs
+++ b/tests/dummy/app/templates/components/tagless-component.hbs
@@ -1 +1 @@
-Hi from tagless2
\ No newline at end of file
+Hi from tagl
\ No newline at end of file
```

**Comment by SirZach** [comment]
i'll try and give an isolated example this weekend

**Comment by MiguelMadero** [comment]
Thanks.

**Comment by MiguelMadero** [comment]
@SirZach did you get a chance to repro? I'll be working on the addon next week and I would like to tackle this issue. I have another branch that takes a different approach and might just address this problem, but I would like to verify.

**Comment by SirZach** [comment]
@MiguelMadero sorry I haven't had time to reproduce this.

**Comment by toranb** [comment]
Closing this out - it's been over a year ;)

**Comment by localpcguy** [comment]
I am seeing this during testing in a component that is NOT a tagless component. Not sure why, but only exists when using the addon. If I can figure out a reproduction, I will.
