### ISSUE TITLE
Problem to find actions in routes

### ISSUE THREAD

**Issue by GCorbel** [toranb/ember-cli-hot-loader#27]
In an ember 2.9 app, without Glimmer 2, I use liquid-fire. I have this template : 

    {{liquid-outlet}}

And I have this error : 

```
Error: Assertion Failed: <tiny@component:liquid-child::ember821> had no action handler for: childDidRender
    at new Error (native)
    at Error.EmberError (http://test.local.com:4200/assets/vendor.js:33084:21)
    at assert (http://test.local.com:4200/assets/vendor.js:20779:13)
    at Object.assert (http://test.local.com:4200/assets/vendor.js:32896:34)
    at Class.send (http://test.local.com:4200/assets/vendor.js:55888:26)
    at Class.superWrapper [as send] (http://test.local.com:4200/assets/vendor.js:38806:22)
    at Class.triggerAction (http://test.local.com:4200/assets/vendor.js:51344:29)
    at Class.sendAction (http://test.local.com:4200/assets/vendor.js:55858:14)
    at http://test.local.com:4200/assets/vendor.js:252364:17
    at tryCatch (http://test.local.com:4200/assets/vendor.js:64955:14)
```

I have the same issue with other components where the action is not specifically defined.

**Comment by MiguelMadero** [comment]
@GCorbel I've not had a chance to repro yet, but my guess is that liquid-outlet might be expecting a particular visual tree (e.g. component hierarchy) and we're missing with it. Basically, we wrap anything that looks like a component into a component that takes care of doing lazy-loading, so we'll rewrite your code example to something like

```
{{#hot-reload-component}}
   {{liquire-outlet}}
{{/hot-reload-component}}
```

If `liquid-outlet`, in turn, uses other child components, we'll do something similar for those. Our goal is to only wrap the components that need hot-reloading (see https://github.com/toranb/ember-cli-hot-loader/issues/14) but right now we don't make a distinction. I suggest two options: 

* Help us with #14, it's a bit easier with https://github.com/toranb/ember-cli-hot-loader/pull/25/
* We can add a "blacklist" or hardcode it to ignore liquid-fire for now (likely the simplest). Here is a diff that could help as a starting point. 

```
diff --git a/addon/mixins/hot-reload-resolver.js b/addon/mixins/hot-reload-resolver.js
index 4f9ef44..81c7a9c 100644
--- a/addon/mixins/hot-reload-resolver.js
+++ b/addon/mixins/hot-reload-resolver.js
@@ -20,6 +20,9 @@ export default Ember.Mixin.create({
     const resolved = this._super(...arguments);
     if (parsedName.type === 'component') {
       if (resolved) {
+        if (parsedName.fullNameWithoutType === 'liquid-fire') {
+          return resolved;
+        }
         return this._resolveComponent(resolved, parsedName);
       }
       if (this._resolveOriginalTemplateForComponent(parsedName)) {
```

I don't want to throw this over the fence. I just wanted to document this here and this could help you or me when we're ready to work on this. I'm in the middle of fixing to other issues and I wanted to wrap those up first. Hope this helps someone.

**Comment by toranb** [comment]
@MiguelMadero I like the idea of creating an explicit black list to avoid something like liquid-fire in this case. Also liked how you mention not throwing it over the wall - just using this to document for now #awesome

**Comment by GCorbel** [comment]
It works with `parsedName.fullNameWithoutType === 'liquid-child'` for liquid-fire but I have problems with other component. I went a little bit deeper and I reproduced the bug with my own component. 

Here is my code : 


app/pods/subscriptions/new/template.hbs



```
{{kh-user-form-has-to-choose-creator submit='submit'}}
<a {{action 'submit' }}>It Works</a>
```



app/pods/subscriptions/new/route.js
```
import Route from 'ember-route';

export default Route.extend({
  actions: {
    submit() {
      console.log('works!');
    }
  }
});
```



app/pods/components/kh-user-form-has-to-choose-creator/template.hbs
```
<a {{action 'submit' }}>It doesn't work</a>
```



app/pods/components/kh-user-form-has-to-choose-creator/component.js
```
import Component from 'ember-component';

export default Component.extend({
  actions: {
    submit() {
      this.sendAction('submit');
    }
  }
});
```

As you can see, it works with a direct route but not with an action from a component.

**Comment by MiguelMadero** [comment]
@GCorbel thanks for the update. I understand the problem a bit better now. Some ideas: 

* We could find a way to handle this actions in the wrapper component and then bubble them. I have now clue where to start since there is no such thing as a "default" action handler. 
* Change the target, this may just work. See example below: 

```diff
diff --git a/addon/components/hot-replacement-component.js b/addon/components/hot-replacement-component.js
index 148eb23..9c49b4e 100644
--- a/addon/components/hot-replacement-component.js
+++ b/addon/components/hot-replacement-component.js
@@ -44,7 +44,7 @@ const HotReplacementComponent = Ember.Component.extend(HotComponentMixin, {
     return Ember.HTMLBars.compile(`
       {{#if hasBlock}}
         {{#if (hasBlock "inverse")}}
-          {{#component wrappedComponentName ${positionalParams} ${attributesMap} as |a b c d e f g h i j k|}}
+          {{#component wrappedComponentName ${positionalParams} ${attributesMap} target=target as |a b c d e f g h i j k|}}
             {{yield a b c d e f g h i j k}}
```
* I'm confident that the AST work (https://github.com/toranb/ember-cli-hot-loader/pull/25) will address this issue since it takes a different approach that won't change the original target. So maybe I just need to block some time and actually wrap that up. I don't remember where I left it, but it may not be that far.....

**Comment by MiguelMadero** [comment]
Oh, adding one more the list (not a global solution, but an alternative): 

* Use closure actions, the benefit here is that those are captured as attrs and bound to the original context and since we pass all the attrs it may just work (untested)

**Comment by MiguelMadero** [comment]
https://github.com/toranb/ember-cli-hot-loader/pull/34 should fix it for classic-actions. Closure actions already work today. I added tests for both on that PR. I still need to move to resume work on the AST which should make some of this patches redundant.

**Comment by MiguelMadero** [comment]
Oh I see. We may have handle and then bubble the actions up from the wrapper, it is doable

**Comment by GCorbel** [comment]
Thanks for your help. I will give it a try later today.

**Comment by GCorbel** [comment]
I tried #34 and it doesn't work. I have the same problem. With Ast, it always reload the whole page. I also tried to add the target and it doesn't work.

I tried with closure actions and it works but I have to change all my project and use it everywhere.

**Comment by GCorbel** [comment]
According to multiple articles on the internet, closure actions seems to be a good practice but I think we will have problems with other components that don't use closure actions.

**Comment by MiguelMadero** [comment]
> In an ember 2.9 app, without Glimmer 2, I use liquid-fire. I have this template :
> I tried #34 and it doesn't work

Unfortunately setting the targetObject doesn't work in 2.9. I had a quick look and this code changed a little bit and now they use `_targetObject` and the old `targetObject` isn't set by default on components, so it's not passed to the "original" component in 2.8+. You could check #34 again it works now on 2.9, but this is feelign less and less reliable. It actually breaks again in Glimmer 2. So while this works in 2.9, I feel like the AST solution is a better bet long term. 

> I tried with closure actions and it works but I have to change all my project and use it everywhere.

While closure actions work, it's a big limitation not to support the traditional actions and it's unrealistic to expect ppl to switch to closure actions just for hot-reload. It's a bit accidental that it works with one and not the other, but I expect that we can get both working reliably soon without breakign Glimmer 2.

Thanks for all your help on this.

**Comment by MiguelMadero** [comment]
Looks like Glimmer 2 was supposed to support `target`, but that didn't work either. [I opened a bug](), while we may not need it, this shows a regression that someone else might ran into. According to https://github.com/emberjs/ember.js/issues/14168 targetObject was for setting, and _targetObject, while it can be read, it has a slightly different behavior. Anytway, reading _targetObject and setting it to targetObject did the trick and #34 now works on 2.7, release and beta (Glimmer 2). Hopefully you this can unblock you while I get a chance to work on the AST branch later this week.

**Comment by MiguelMadero** [comment]
@oligriffiths can you have a look at https://github.com/toranb/ember-cli-hot-loader/pull/34/files  and see if it fixes that? Last time I checked it didn't work in glimmer2 so we didn't merge that. 
The AST branch has a completely different approach so it works there, but the AST branch has a different issue with glimmer 2 that I have not been able to figure out. Maybe we can pair on this and see if we can get to the bottom of it next week....
