### ISSUE TITLE
positionalParams.join is not a function

### ISSUE THREAD

**Issue by corrspt** [toranb/ember-cli-hot-loader#30]
Hi,

In my app, but I get the following error:

EDIT: I'm using ember 2.9.0, with ember-cli 2.9.1 and a bunch of other addons.
I'm using pods structure, but I have a few components that are not in pod structure.

```
hot-replacement-component.js:41 Uncaught TypeError: positionalParams.join is not a function(…)
(anonymous function) @ hot-replacement-component.js:41ComputedPropertyPrototype.get @ 
```

The code in question is here:
![bug-hot-loader](https://cloud.githubusercontent.com/assets/789263/20410151/ab6212b4-ad13-11e6-9dff-28e6330281b8.jpg)

So the `positionalParams` variabled is usually an array, but there's something on my app that in this particular instance makes it a string with the value `params` and the app does not load. 

I tracked (at least part of) the problem to my `w-sidebar` component which has the following code:

``` 
<li>{{#link-to 'user-settings'}}{{fa-icon 'user'}} {{t 'sidebar.user-profile'}}{{/link-to}}</li>
``` 
If this code is present, the app blows up with this error. Any ideas?

**Comment by MiguelMadero** [comment]
Hi @corrspt this seems to be my standard answer, it will be fixed by https://github.com/toranb/ember-cli-hot-loader/pull/25 which moves away from the [component-apply](https://github.com/zenefits/ember-component-apply) technique we use here. There might be a quick fix until we land #25, but I couldn't repro, I tried link-to and that works fine, so it may be fa-icon or `t`. I'm guessing that `t` is a helper and not a component so it's more likely `fa-icon`. What's the addon you're using there?

**Comment by MiguelMadero** [comment]
I just repro'd after installing https://github.com/martndemus/ember-font-awesome

**Comment by MiguelMadero** [comment]
The issue comes from https://github.com/martndemus/ember-font-awesome/blob/master/addon/components/fa-icon.js#L101 where they use a string. I had no idea it's valid http://emberjs.com/api/classes/Ember.Component.html#property_positionalParams so we need to support both. PR coming.

**Comment by MiguelMadero** [comment]
PR on https://github.com/toranb/ember-cli-hot-loader/pull/32

**Comment by corrspt** [comment]
Hi @MiguelMadero, thanks for the quick reply.

Yes, `t` is a helper from [ember-i18n](https://github.com/jamesarosen/ember-i18n) and `fa-icon` is from [ember-font-awesome](https://github.com/martndemus/ember-font-awesome).

I've installed the ember-cli-hot-loader using the [PR you linked to](https://github.com/toranb/ember-cli-hot-loader/pull/32) and the error does not occur any more (and my initial page, loads!)

Now that I can load my application I get a bunch of different errors on different places, but in my main page I have a component named `certificate-dashboard-table` (which does not yield) and has a simple template (a table essentialy) and I tried adding a random string to the template just to see if it would reload, and I get the following error:

![cli-hot-reload](https://cloud.githubusercontent.com/assets/789263/20456358/451625bc-ae6d-11e6-8457-472b46872534.jpg)

Should I open another issue when you merge that PR?

**Comment by MiguelMadero** [comment]
Are you using rootURL? (See your config/environment) if thats the case,
there is another open pr for this.

**Comment by corrspt** [comment]
@MiguelMadero Yup, using the rootUrl :)

I'll wait for the PR then ;) Thanks for such a quick reply (and for the awesome idea on this addon)

**Comment by MiguelMadero** [comment]
Ill let you know here once we release these two changes.

**Comment by corrspt** [comment]
Thanks! I'm subscribing to the project, but I appreciate it :)

**Comment by toranb** [comment]
thanks for reporting this @corrspt ! I just learned about the approach font-awesome uses as a co-worker started doing something similar on our internal projects (reduces the boilerplate required for default params/attrs like I often see). I think the rootURL is g2g (and should be merged this week) but the other I'd like to see an addition to the dummy app (adding something basic w/out having to include font awesome if possible). I'm planning to look at this later today if it's cool w/ you @MiguelMadero (just so we have one in the dummy app that I can test/play around with)

**Comment by corrspt** [comment]
Glad I could help! I really like this addon, hope you guys can make it even more awesome.

**Comment by MiguelMadero** [comment]
Released as 0.1.3

**Comment by MiguelMadero** [comment]
> I'm planning to look at this later today if it's cool w/ you @MiguelMadero

@toranb sorry about this. I didn't check this before pushing. If you want to take any of the other issues, please assign them to yourself and I'll make sure I leave them with you.

**Comment by toranb** [comment]
@MiguelMadero ah, no worries :) you do beyond exceptional work so I'm thankful either way! I just published this to npm so it should be npm install-able now :)

**Comment by MiguelMadero** [comment]
Thanks. Doh! Always assumed "ember release" would npm publish. Im wondering
if my other addons are missing it as well lol.
