### ISSUE TITLE
Not compatible with ember-component-css

### ISSUE THREAD

**Issue by oligriffiths** [toranb/ember-cli-hot-loader#35]
Hey,

When installing this addon, it seems to wipe out the auto-generated class name that's applied to a components element by https://github.com/ebryn/ember-component-css causing styles to break.

Not sure whether the issue is within this addon or ember-component-css, but manual `classNames` property works, but the auto generated class name is not.

Referenced issue https://github.com/ebryn/ember-component-css/issues/165

**Comment by toranb** [comment]
https://github.com/ebryn/ember-component-css/issues/165

Right on - I ran into this myself and forked ember-component-css to work around it.

https://github.com/toranb/ember-component-css/commit/29f63f03ea40c9b3fc490174ae5718cfa2801a0a

If you could ping the guys on ember-component-css it might help them see that they do indeed need to offer an extension point so we can override it for special cases like this

**Comment by toranb** [comment]
Closing this out now that `ember-component-css` v0.3.0 has an extension point (making it hot reload friendly). Below is a commit showing how to unlock this for anyone watching

https://github.com/toranb/ember-redux-yelp/commit/0efec8c0319edbd3f7ddda79e1e3ff87d3b212ef

**Comment by oligriffiths** [comment]
@tornab is there any way we can include that mixin in this repo and provide instructions on how to setup with component css?

**Comment by toranb** [comment]
@oligriffiths it's possible - when the AST rewrite lands I'm not certain we will need it (cc @MiguelMadero) so it's possible we could remove it (worst case). I'm torn because I also think maybe we could just add what is required to the README (not much code/ not everyone is using the ember-component-css project)

**Comment by MiguelMadero** [comment]
I feel like a lot of things are waiting on the AST and we should just push in that direction, but also we have been waiting for it for so long that I don't want to block alternative solutions. All that said, I think that README instructions is a reasonable approach in this case.
