### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by victornamuso** [toranb/ember-cli-hot-loader#38]
Have tried to implement in a new project, as well as cloned this and ran the dummy. No matter what I do, the page still wants to refresh. I figure it has to be something environmental about my machine.  Where should I start troubleshooting?

**Comment by victornamuso** [comment]
I'm on macOS Sierra, running Ember 2.9.

I was able to work through this a little bit, but haven't completed resolved it. I have completely resolved it for the cloned app and dummy. Watchman seems to somehow be involved. I was able to uninstall and reinstall watchman and hot-reload job followed. I was also able to get this working on a new project from scratch. On two existing projects that I'm working on, no such success. My next step will be to clone the problematic projects to a fresh VM or another laptop that I have which is a clean install.

**Comment by toranb** [comment]
@victornamuso thanks for taking a run at this to provide more detail. I don't use watchman myself these days but maybe I should :)

When you provide some additional info it may help us identify an issue/or at the very least add something to the README so others are aware of the incompatibility
