### ISSUE TITLE
DEPRECATION: ember-getowner-polyfill is now a true polyfill

### ISSUE THREAD

**Issue by neojp** [toranb/ember-cli-hot-loader#39]
I'm not sure if it's possible to dynamically load the polyfill based on the Ember version to avoid the deprecation notice.

Regardless, I'll leave this here to let you know about the deprecation notice been thrown on the latest version of **Ember 2.11.0**

http://emberjs.com/deprecations/v2.x/

**Comment by toranb** [comment]
@neojp sorry for the delay -we actually merged the `ember-getowner-polyfill` update a week or two back but I failed to publish a new version. I just pushed up v0.1.4 and it's g2g :)

Sorry for the delay on my end!

https://github.com/toranb/ember-cli-hot-loader/commit/a73fd33fb861537cb8af955a521a10e664eb3e87

**Comment by neojp** [comment]
That's great! Thank you. No need for apologies, I'm very thankful for your work on this addon.
