### ISSUE TITLE
Hot loader v0.1.5 broken with pods and ember-cli v2.11

### ISSUE THREAD

**Issue by toranb** [toranb/ember-cli-hot-loader#43]
After v0.1.5 was released I found pods doesn't reload when using ember-cli v2.11.1 (no bower ember source code)

https://github.com/toranb/misc-reload-example/tree/branches/pods

When I don't use pods (classic layout) it seems to hot reload just find using ember-cli v2.11.1

https://github.com/toranb/misc-reload-example/tree/branches/classic

@oligriffiths this similar to what you've found recently ?

**Comment by oligriffiths** [comment]
If there's a podModulePrefix it should work just fine (does for me) the issue is when that's not defined and the requirejs path is incorrect.

**Comment by toranb** [comment]
@oligriffiths what file in that project above ^^ will solve that here? I did think to myself it was related to the stuff you mentioned (that bug I think it was) ?

**Comment by oligriffiths** [comment]
In ember-cli-build.js defining a podModulePrefix path, even if it's the same as the modulePrefix path and it should work just fine

**Comment by toranb** [comment]
@oligriffiths yup - that fixed it :)

https://github.com/toranb/misc-reload-example/commit/99280f6370c360f587b3032d12e21948bf3d3729

**Comment by oligriffiths** [comment]
@toranb https://github.com/toranb/ember-cli-hot-loader/pull/41 fixes this
