### ISSUE TITLE
Hotreload for template only components, mixed component+template and addon components

### ISSUE THREAD

**Issue by MiguelMadero** [toranb/ember-cli-hot-loader#5]
Today it only works for inline templates like: 

```
import Ember from 'ember';
import hbs from 'htmlbars-inline-precompile';

export default Ember.Component.extend({
  layout: hbs`
    <h1>hello world</h1>
  `
});
```

We need to support the other three common cases: 

1. Component and template on a separate file. 
2. Components that only have an .hbs file, but not an JS file. 
3. Components in addon where the template is imported as an ES6 module.

**Comment by MiguelMadero** [comment]
@toranb you mentioned that you fixed all or some of these scenarios, do you want to take this or link to your solution here?

**Comment by toranb** [comment]
https://github.com/toranb/ember-hot-reload-spike/commit/a1e22005d05f2db84e7a5796cded2927cb87a34f

I know you didn't like the resolver hacking but it did work :)

give it a look and let me know your thoughts

**Comment by MiguelMadero** [comment]
Thanks, that's what I was looking for. 

I left a few comments, but nothing major. Looks good! (Good in the current context, most of what we're doing is a bit hacky and fragile, but this isn't as bad as most of the other stuff I wrote. The only concern is that most of the stuff is isolated, and the more we mess with the resolver the more we risk breaking apps, but we can address that later).
