### ISSUE TITLE
ember-cli v2.13.0-beta.3 broke the hot reloader

### ISSUE THREAD

**Issue by toranb** [toranb/ember-cli-hot-loader#50]
I upgraded from ember-cli v2.13.0-beta.2 => ember-cli v2.13.0-beta.3 today and the hot reloader is busted :(

I narrowed the issue down to this 1 line

https://github.com/ember-cli/ember-cli/pull/6905/files#diff-8c2a707dbfbdde1d38720af1fc8c354aL34

The upgrade to ember-load-initializers to v1.0.0 is the issue (both ember-cli v2.13.0-beta.2 and v2.13.0-beta.3 work fine when I bump back to the previous)

`"ember-load-initializers": "^0.6.0"`

When I look at the changelog for the above ^^ I see a move to babel 6 along with a bump of ember-cli-htmlbars-inline-precompile (from 0.3.1 => 0.4.0-beta.2)

https://github.com/ember-cli/ember-load-initializers/commit/b2b4054865ef77db9a8804b2981b12e9f608cacb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R46

I'll need to chat w/ @rwjblue to understand this further

**Comment by rwjblue** [comment]
Please explain what "broke" means? There was an error? The functionality no longer worked? Something else?

**Comment by toranb** [comment]
@rwjblue took 2 more swings at this and it's clear I didn't dump my local node_modules well enough. All seems good with ember-cli v2.13.0-beta.3 :) :) :)

Sorry for the false alarm everyone
