### ISSUE TITLE
Build issue on Windows & Ember 2.18

### ISSUE THREAD

**Issue by lifeart** [toranb/ember-cli-hot-loader#63]
In first build time I have:

ENOENT: no such file or directory, open 'C:\app-name\frontend\tmp\sou
rce_map_concat-input_base_path-HCn1vPtb.tmp\C:\app-name\frontend\node
_modules\ember-source\dist\ember-template-compiler.js'

But, `ember-source\dist\ember-template-compiler.js` exists and `sou
rce_map_concat-input_base_path-HCn1vPtb.tmp` available and it's folder

**Comment by lifeart** [comment]
But, if I change 
`app.import(npmPath)`
to 
`app.import('../../node_modules/ember-source/dist/ember-template-compiler.js');`
all OK.

**Comment by toranb** [comment]
What folder are you running `ember serve` from when you use this? From your path it seems like you might have a top level folder named `app-name` and within that a folder called `frontend` (guessing that is the ember app?) -just curious if running from `app-name` differs from `frontend`

**Comment by lifeart** [comment]
@toranb, sorry for confusing paths, my project looks like
`root/src/frontend` and I run `ember s` from `root/src/frontend`

`app-name\frontend` -> `frontend`

**Comment by toranb** [comment]
Before we dive into the specifics of your node install/ symlinks/ folder structure -would you mind cloning this demo app and giving it a go on your windows machine?

https://github.com/toranb/ember-hot-reload-demo

be sure to run `ember s` using the local^ ember-cli (not a globally installed ember-cli if that makes sense). You can do this by first doing a clone/ then run yarn/ and finally

```./node_modules/ember-cli/bin/ember s```

**Comment by lifeart** [comment]
Can reproduce my issue on Windows using this project setup  - 
[lwl-up.zip](https://github.com/toranb/ember-cli-hot-loader/files/1988520/lwl-up.zip)

**Comment by lifeart** [comment]
@toranb latest version in NPM 
' The error message above mentions nodeModulesPath and that was removed before the v0.3X release a month or so back.' - yeah, but this is only deprecation warning, real error on next line - 

ENOENT: no such file or directory, open 'C:\Users\lifeart\Documents\Repositories\lwl-up\tmp\source_map_concat-input_base
_path-5K4jXeJs.tmp\C:\Users\lifeart\Documents\Repositories\lwl-up\node_modules\ember-source\dist\ember-template-compiler
.js'

> Does chrome "pause" 
- yes

**Comment by toranb** [comment]
@lifeart I don't have a windows machine myself to triage this but I'm happy to pair up at some point to find out why this isn't "hot reloading" - you up for something like this over screen hero? If so ping me via email so we can schedule it ;)

toranb [at] gmail

**Comment by vlascik** [comment]
@toranb I'm trying to get hot-reload to work on Windows as well, and I have I think two problems:

First, when I run the demo, `modulePath` in `reload()` is set to `P:\ember-hot-reload-demo\app\templates\components\todo-item.hbs`, which is checked by regexps in `matchesClassicConvention()` that use posix paths: `new RegExp(regexEscape('templates/components/' + componentName + '.hbs') + '$'`. This is never going to match, after I tried to change the regexp to windows path separator, reload worked.

Second, in my regular app, `modulePath` is somehow set just to `assets/my-app.js`, not the component.js or template.hbs. Debug log shows entries like these:
```
  ember-cli:watcher [styles#3624 -> BroccoliMergeTrees#3625 -> SassCompiler#3626] didChange { directory: 'P:\\Project\\tmp\\broccoli_merge_trees-output_path-9WFplDpM.tmp', graph: Node:2077 subtrees: 5, outputChanges: [ 'assets/my-app.js', 'assets/my-app.map' ], totalTime: 2926207010, filePath: 'P:\\Project\\app\\components\\my-component\\template.hbs___jb_tmp___' } +1ms
...
  fs-tree-diff: [styles#3624 -> BroccoliMergeTrees#3625 -> SassCompiler#3626] invalidation reason: 
  fs-tree-diff: before Entry { relativePath: 'assets/my-app.js', basePath: 'P:/Project/tmp/broccoli_merge_trees-output_path-9WFplDpM.tmp', mode: 33206, size: 139841, mtime: 1525961500995 }
  ember-cli:live-reload: [styles#3624 -> BroccoliMergeTrees#3625 -> SassCompiler#3626] files %a [ 'assets/my-app.js' ] +0ms
```

I don't quite get why would SassCompiler invalidate my-app.js. Any ideas on where this could come from or why?.

**Comment by toranb** [comment]
@vlascik great find on the regex for windows! After that fix it truly "hot reloads" eh? You care to PR that small change so we can get this working for windows users :) I'd appreciate it if you've got the bandwidth this week/weekend

About the 2nd point - ember-cli itself does "hot reload" the css changes you've made (nothing this addon does as ember-cli offers this out of the box I believe).

**Comment by toranb** [comment]
@lifeart I've updated the modulePath to better support hot reloading from windows. Would you mind pulling the latest example app and re-installing `ember-cli-hot-loader` v0.4.0 to confirm it is/ or is not working on windows?

https://github.com/toranb/ember-hot-reload-demo/commit/a5e093721e2e941ee558abc6fad11f4a19fe4c2c

**Comment by toranb** [comment]
@vlascik also happy to have you try this out btw - let me know if the v0.4.0 release fixed the path issue when you've got time ;)

**Comment by lifeart** [comment]
@toranb, yes! Now it's working on windows in `toranb/ember-hot-reload-demo`

**Comment by toranb** [comment]
@lifeart good news! I'm planning to close this out for now as windows does appear to be working. If you want to triage your specific env further, would you mind throwing that project structure up on github? I know you had a zip file linked above but I'd love to simply fork it /hack around if necessary

**Comment by toranb** [comment]
@vlascik @lifeart either of you have some time this week to test the v1.0.1 release on windows? I'm hopeful it's solid ;) but without a windows dev machine myself I thought to reach out and confirm it's functional /or busted. I appreciate your time -thank you both!

**Comment by lifeart** [comment]
Sure, np

**Comment by vlascik** [comment]
@toranb updated the demo to the latest version with 1.0.1, tried in Firefox and Edge, Firefox works, Edge does a full reload.
Btw. you can download free 90-day Windows VMs here https://developer.microsoft.com/en-us/windows/downloads/virtual-machines or here 
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
Seems that the evaluation can be extended like this afterwards: https://community.dynamics.com/ax/b/newdynamicsax/archive/2017/08/24/windows-evaluation-license-expiring-on-local-development-vms
