### ISSUE TITLE
Error when passing a DOM event handling function to a component.

### ISSUE THREAD

**Issue by lukemelia** [toranb/ember-cli-hot-loader#68]
With `{{foo click=someFunc}}` and this addon installed, rendering triggers a debug assertion:

`Assertion Failed: You can not define a function that handles DOM events in the `<dummy@component:foo::ember451>` tagless component since it doesn't have any DOM element.`

**Comment by toranb** [comment]
Thanks for reporting this @lukemelia! I just knew [this commit](https://github.com/toranb/ember-cli-hot-loader/commit/56a5fb07511a3d9484a58880e9b0a2efeafa1c08#diff-8d9f64b99fb73be5388818039649c82f) would come back to haunt me ;)

I'm recovering this week/weekend from LASIK but when I'm back @100% next week I'll dive in and see what we can do to support this type of action!

**Comment by localpcguy** [comment]
Might also look at the discussion in #24 as it seems related

**Comment by toranb** [comment]
@lukemelia trying to repro this tonight and found a way to land classic actions w/out a warning in #73 . I'm curious if you could twiddle up something small in the next week just to show end to end what you had in mind. I'm feeling like an action imposter all of the sudden so any guidance would help educate me and I'll surely owe you one :)

Thanks again!

**Comment by toranb** [comment]
@lukemelia I finally got an example app to repro this :)

https://github.com/toranb/hot-reloader-actions-tagless-triage

**Comment by toranb** [comment]
Some good news! If I simply remove the line `tagName: ""` from our wrapper component this problem disappears completely. I remember the ember 3.1/3.2 beta blog mentioning that "template only glimmer components" could remove this extra div element using the optional flag `ember feature:enable template-only-glimmer-components` so ... I'm curious when this lands if we just get the same "tagless" behavior.

I'm planning to pull this^ and do a v1.0 release w/ a few other changes, like removing the targetObject deprecation warnings, so users can give it another go and provide feedback. If this creates a visual issue for people they can simply punt on this addon until we know more about the "template only glimmer components" feature. At best, this should give people stuck with this action error another shot at hot reloading :)

I've got 1 blocker before this v1.0 release that I'm hoping to resolve this weekend/early next week.

**Comment by toranb** [comment]
I published v1.0.0 this morning and tested it w/ a handful of ember 2.18+ apps so for anyone having this issue please give it another go if you've got some bandwidth and still want to get fast feedback :)
