### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by jbryson3** [toranb/ember-cli-hot-loader#75]
Thought I'd try out the hot-loader for a component that I'm working on. Unfortunately with a fresh install I'm getting an error when I `ember s`

```
Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at HotReloader (/Users/jbryson3/code/arbiter/node_modules/ember-cli-hot-loader/lib/hot-reloader.js:19:34)
    at Class.serverMiddleware (/Users/jbryson3/code/arbiter/node_modules/ember-cli-hot-loader/index.js:13:51)
    at ExpressServerTask.<anonymous> (/Users/jbryson3/code/arbiter/node_modules/ember-cli/lib/tasks/server/express-server.js:102:22)
    at /Users/jbryson3/code/arbiter/node_modules/promise-map-series/index.js:11:14
    at tryCatch (/Users/jbryson3/code/arbiter/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/jbryson3/code/arbiter/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/jbryson3/code/arbiter/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/jbryson3/code/arbiter/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I previously did not have a app/resolver.js file.
Ember-cli: 2.13.2
Node: 8.11.2

Any ideas?

**Comment by toranb** [comment]
From that stacktrace it appears the array for supported types isn't coming thru. Could you log from the index.js right before the lib func is invoked (in the server middleware hook) to learn why that configuration is undefined?

**Comment by toranb** [comment]
Also, this is an ember app not an addon or engine right?

**Comment by jbryson3** [comment]
Yes, it's an ember app, not an addon or engine.

It seems that the `this` context is lost between the `included` hook and the `serverMiddleware` hook

```js
module.exports = {
  name: 'ember-cli-hot-loader',
  serverMiddleware: function (config){
    console.log(this.foo); //undefined
  },
  included: function (app) {
    this.foo = 'bar';
  }
};
```

**Comment by toranb** [comment]
Interesting ... I'm still curious about this mention in your comment

```I previously did not have a app/resolver.js file```

So you didn't have a resolver file before you ran this ember install?

**Comment by toranb** [comment]
@jbryson3 I created an ember-cli v2.13.2 app and it seems to work w/ the hot reloader. Can you clone this and see if it works for you?

https://github.com/toranb/emberCliTwoExample

**Comment by jbryson3** [comment]
@toranb Thanks for creating a repo to try and reproduce the issue. Your repo works. There must be something going on with our app that's messing with the addon hooks somehow. 

I'll try and narrow it down from my end. 

And yes, previously, we did not have an app/resolver.js file. I'm assuming that the default resolution is provided by ember-resolver (npm dependency) but not sure

**Comment by jbryson3** [comment]
@toranb The problem was entirely on my end. In our `ember-cli-build.js` we were not actually using the defaults to boot up the app.

```js
module.exports = function(/* defaults */) {
  let opts = {
    // bunch of configs
  };
  let app = new EmberApp(opts, {});
  return app.toTree();
}
```

Why we were doing this is beyond me.

Changed it to use defaults, and it's working. 
```js
let app = new EmberApp(defaults, opts);
```

Looking forward to using your addon now. Thanks again for your time helping me narrow down the issue. 

P.S. Enjoyed hearing you on the ember-map podcast
