### ISSUE TITLE
Proper child components destroy on teardown

### ISSUE THREAD

**Issue by lifeart** [toranb/ember-cli-hot-loader#85]
I have `power-select` wrapper component, with div and custom logic, it it's open and I trying to update component via hot-loader, I get errors like `cannot call send on destroyed object` and `cannot call set on destroyed object`

**Comment by toranb** [comment]
@lifeart if you get time could you throw together a gist or twiddle with your example so I can further triage what is happening?

**Comment by toranb** [comment]
@lifeart this still a known issue in the latest release?

**Comment by lifeart** [comment]
Looks like problem fixed by https://github.com/toranb/ember-cli-hot-loader/pull/95
